"""
Adaptive Learning Path Models

Stores personalized learning recommendations generated by LLM analysis.
"""

from sqlalchemy import Column, String, Integer, Text, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid

from app.database import Base


class AdaptiveRecommendation(Base):
    """
    Stores personalized learning path recommendations.
    
    Generated by LLM analysis of student's learning patterns.
    Cached to avoid redundant LLM calls (GET /latest returns cached version).
    
    Constitutional Compliance:
    - Premium-gated only (Principle VIII)
    - User-initiated (Principle VIII)
    - Cost-tracked via llm_usage_id (Principle X)
    """
    
    __tablename__ = "adaptive_recommendations"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Structured recommendation data (stored as JSONB for flexibility)
    recommended_chapters = Column(JSONB, nullable=False)
    # Example: [
    #   {"chapter_id": "ch-003", "title": "...", "priority": 1, "reason": "...", "estimated_time_minutes": 30}
    # ]
    
    weak_areas = Column(JSONB, nullable=False)
    # Example: ["MCP basics", "Agent Skills configuration"]
    
    strengths = Column(JSONB, nullable=False)
    # Example: ["Claude Agent SDK", "Tool integration"]
    
    overall_assessment = Column(Text, nullable=False)
    # LLM's narrative summary of student's progress
    
    suggested_daily_minutes = Column(Integer, nullable=True)
    # Recommended daily study time
    
    # Link to LLM usage for cost tracking
    llm_usage_id = Column(UUID(as_uuid=True), ForeignKey("llm_usage.id"), nullable=True)
    llm_usage = relationship("LLMUsage")
    
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow, index=True)
    
    # Relationships
    user = relationship("User", back_populates="adaptive_recommendations")
    
    def __repr__(self):
        return f"<AdaptiveRecommendation(user_id={self.user_id}, created={self.created_at})>"
    
    def to_dict(self) -> dict:
        """Convert to dictionary for API response"""
        return {
            "recommended_chapters": self.recommended_chapters,
            "weak_areas": self.weak_areas,
            "strengths": self.strengths,
            "overall_assessment": self.overall_assessment,
            "suggested_daily_goal_minutes": self.suggested_daily_minutes
        }


# Index for efficient latest recommendation queries
Index(
    "ix_adaptive_recommendations_user_created",
    AdaptiveRecommendation.user_id,
    AdaptiveRecommendation.created_at.desc()
)
